import React from 'react';
import { CheckCircle2, Cpu, Network, Radar, ShieldCheck, Cloud } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useLanguageContext } from '../../contexts/LanguageContext';
import { VENDOR_EVIDENCE } from '../../data/vendorEvidence';
import organization from '../../data/organization.json';
import authoritySources from '../../data/authoritySources.json';
import { ActionLink, CheckList, PageHero, PageShell, SourceLink, tx } from './SitePagePrimitives';

const AboutPage: React.FC = () => {
  const { isEnglish } = useLanguageContext();
  const capabilities = [
    { icon: Network, title: { zh: '整合能力', en: 'Integration' }, body: { zh: '以 API、事件、身分與權限邊界連接既有系統，保留來源、狀態與責任脈絡。', en: 'Connect existing systems through APIs, events, identity, and permission boundaries while preserving source, state, and ownership.' } },
    { icon: ShieldCheck, title: { zh: '治理能力', en: 'Governance' }, body: { zh: '關鍵通知、付款、正式會計、驗收與狀態變更，都保留人員核准與稽核紀錄。', en: 'Critical notifications, payments, formal accounting, acceptance, and state changes keep human approval and an audit trail.' } },
    { icon: CheckCircle2, title: { zh: '交付能力', en: 'Delivery' }, body: { zh: '從可操作的小範圍開始。用實際資料、測試案例、驗收指標與維運責任決定是否擴充。', en: 'Start with a small, operable scope. Real data, test cases, acceptance metrics, and operating ownership decide when to expand.' } }
  ];
  const solutions = [
    { icon: Cloud, label: { zh: 'EudTech 雲端服務', en: 'EudTech cloud services' }, title: { zh: 'AWS 雲端銷售服務', en: 'AWS cloud sales' }, body: { zh: '從 AWS 服務選型與預算估算，連接採購報價、建置移轉與維運規劃。可供服務與商務條件依正式報價確認。', en: 'Connect AWS service selection and budget planning with procurement quotes, deployment, migration, and support scope. Availability and commercial terms are confirmed in the formal quote.' }, href: '/solutions/aws', source: { href: 'https://aws.amazon.com/', label: { zh: 'AWS 原廠服務介紹', en: 'AWS service information' } } },
    { icon: ShieldCheck, label: { zh: 'EudTech 顧問服務', en: 'EudTech advisory' }, title: { zh: 'PQC 後量子密碼遷移', en: 'PQC migration advisory' }, body: { zh: '從密碼資產盤點、風險排序到可控試點與遷移治理，建立可審查的證據、責任與回復路徑。', en: 'Move from cryptographic inventory and risk priorities to controlled pilots and migration governance with reviewable evidence, ownership, and rollback paths.' }, href: '/solutions/pqc', source: { href: 'https://www.nist.gov/pqc', label: { zh: 'NIST 後量子密碼專頁', en: 'NIST post-quantum cryptography' } } },
    { icon: Cpu, label: { zh: 'EudTech × Comino', en: 'EudTech × Comino' }, title: { zh: 'AI 運算基礎設施', en: 'AI compute infrastructure' }, body: { zh: '將模型、模擬與運算需求轉成 Comino 液冷工作站或伺服器的配置、報價與驗收計畫。', en: 'Turn model, simulation, and compute needs into Comino liquid-cooled workstation or server configurations, quotes, and acceptance plans.' }, href: '/solutions/ai-infrastructure', source: VENDOR_EVIDENCE.comino.sources.blackwell },
    { icon: Radar, label: { zh: 'EudTech × Cyabra', en: 'EudTech × Cyabra' }, title: { zh: '社群情報與品牌保護', en: 'Social intelligence and brand protection' }, body: { zh: '以 Cyabra 分析帳號真實性、敘事、協調活動與警示。支援品牌、公關、資安與公部門決策。', en: 'Use Cyabra for profile authenticity, narratives, coordinated activity, and alerts across brand, communications, security, and public-sector decisions.' }, href: '/solutions/social-intelligence', source: VENDOR_EVIDENCE.cyabra.sources.authenticity }
  ];
  const customers = [
    { zh: '需要 AWS 服務選型、用量預算與採購窗口的中小企業', en: 'SMEs needing AWS service selection, usage budgeting, and a procurement contact' },
    { zh: '需要將網站、應用、資料庫或備份移轉至雲端的團隊', en: 'Teams moving websites, applications, databases, or backups to the cloud' },
    { zh: '需要多 GPU、液冷、機架部署與正式驗收的研究室、企業與公部門', en: 'Labs, enterprises, and public institutions requiring multi-GPU, liquid cooling, rack deployment, and formal acceptance' },
    { zh: '需要分析假帳號、敘事與協調行為的品牌、公關、資安與政策團隊', en: 'Brand, communications, security, and policy teams analysing fake profiles, narratives, and coordinated behaviour' },
    { zh: '需要把範圍、交付物、來源證據與責任邊界寫清楚的採購單位', en: 'Procurement teams that need scope, deliverables, source evidence, and responsibility boundaries stated clearly' }
  ];

  const structuredData = [
    {
      '@context': 'https://schema.org', '@type': 'AboutPage', '@id': 'https://eudaemonia.tech/about/#aboutpage',
      url: 'https://eudaemonia.tech/about/', name: isEnglish ? 'About Eudaemonia Technology' : '關於 EudTech｜優達盟資訊科技',
      about: { '@id': organization['@id'] }, mainEntity: { '@id': organization['@id'] },
      citation: authoritySources.sources.map(source => source.url)
    }
  ];

  return <PageShell title={{ zh: '關於 EudTech｜優達盟資訊科技', en: 'About Eudaemonia Technology' }} description={{ zh: '了解 EudTech PQC 遷移顧問、AWS 雲端銷售與導入、Comino 液冷 AI 運算、Cyabra 社群情報，以及可核對的公司與原廠合作資料。', en: 'EudTech helps enterprises, researchers and public institutions plan PQC migration, AWS cloud, AI infrastructure and social intelligence delivery, with verifiable company and manufacturer sources.' }} path="/about" structuredData={structuredData}>
    <PageHero eyebrow={{ zh: '關於 EudTech', en: 'About EudTech' }} title={{ zh: '把技術、流程與決策接在一起', en: 'Connect technology, operations, and decisions' }} lead={{ zh: '優達盟資訊科技有限公司（EudTech）協助企業、研究單位與公部門，把 PQC 遷移、AWS 雲端服務、運算設備與情報工具導入實際工作流程。需求、來源、核准、驗收與責任都會寫清楚。', en: 'Eudaemonia Technology (EudTech) helps enterprises, research teams, and public institutions put PQC migration, AWS cloud services, compute systems, and intelligence tools into practical workflows. Requirements, sources, approvals, acceptance, and ownership are written down.' }} isEnglish={isEnglish} image="/brand-provenance/eudtech-brand-delivery.webp" imageAlt={{ zh: 'EudTech 交付、整合與驗收的品牌情境圖', en: 'Brand scene for EudTech delivery, integration, and acceptance' }} imagePosition="center" actions={<ActionLink href="/contact">{isEnglish ? 'Work with EudTech' : '與 EudTech 合作'}</ActionLink>} />

    <section className="py-20"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">{isEnglish ? 'EudTech delivery scope' : 'EudTech 交付範圍'}</p><h2 className="mt-4 text-3xl font-bold tracking-tight">{isEnglish ? 'A Taiwan-based team owns requirements and delivery across four solution lines' : '由台灣窗口負責四條解決方案的需求與交付'}</h2><p className="mt-5 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'Each card states what EudTech owns, where delivery ends, and which vendor evidence applies.' : '以下說明每條方案的 EudTech 負責範圍、交付邊界與原廠依據。'}</p></div><div className="mt-10 grid gap-6 sm:grid-cols-2">{solutions.map(({ icon: Icon, label, title, body, href, source }) => <article key={tx(title, isEnglish)} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-4"><Icon className="h-7 w-7 text-cyan-600 dark:text-cyan-300" /><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs font-semibold text-cyan-800 dark:bg-cyan-950 dark:text-cyan-200">{tx(label, isEnglish)}</span></div><h3 className="mt-6 text-xl font-semibold">{tx(title, isEnglish)}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{tx(body, isEnglish)}</p><div className="mt-5 flex flex-col items-start gap-3"><Link to={href} className="text-sm font-semibold text-cyan-700 dark:text-cyan-300">{isEnglish ? 'View delivery scope →' : '查看交付範圍 →'}</Link>{source && <SourceLink href={source.href} label={source.label} isEnglish={isEnglish} />}</div></article>)}</div></div></section>

    <section id="verified-company-identity" className="scroll-mt-24 border-y border-slate-200 bg-white py-14 dark:border-slate-800 dark:bg-slate-950"><div className="mx-auto max-w-7xl px-6 lg:px-8"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">{isEnglish ? 'Verified company identity' : '可核對的公司與合作身分'}</p><h2 className="mt-4 text-2xl font-bold">{isEnglish ? organization.alternateName[0] : organization.legalName}</h2><dl className="mt-7 grid gap-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="font-semibold">{isEnglish ? 'Taiwan Unified Business No.' : '統一編號'}</dt><dd className="mt-1 text-slate-600 dark:text-slate-300">{organization.taxID}</dd></div><div><dt className="font-semibold">{isEnglish ? 'Established' : '設立日期'}</dt><dd className="mt-1 text-slate-600 dark:text-slate-300"><time dateTime={organization.foundingDate}>{organization.foundingDate}</time></dd></div><div><dt className="font-semibold">{isEnglish ? 'Registered office' : '登記地址'}</dt><dd className="mt-1 text-slate-600 dark:text-slate-300">{isEnglish ? '14F., No. 8, Ln. 77, Sec. 2, Zhongshan N. Rd., Zhongshan Dist., Taipei City, Taiwan' : `${organization.address.addressRegion}${organization.address.addressLocality}${organization.address.streetAddress}`}</dd></div><div><dt className="font-semibold">{isEnglish ? 'Evidence last checked' : '證據查核日期'}</dt><dd className="mt-1 text-slate-600 dark:text-slate-300"><time dateTime={authoritySources.lastVerified}>{authoritySources.lastVerified}</time></dd></div></dl><div className="mt-9 grid gap-5 md:grid-cols-3">{authoritySources.sources.map(source => <article key={source.id} className="rounded-xl border border-slate-200 p-5 dark:border-slate-800"><h3 className="font-semibold">{tx(source.title, isEnglish)}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{tx(source.description, isEnglish)}</p><a className="mt-4 inline-block text-sm font-semibold text-cyan-700 underline underline-offset-4 dark:text-cyan-300" href={source.url} target="_blank" rel="noopener noreferrer">{isEnglish ? 'Open original source' : '開啟原始來源'}</a></article>)}</div><p className="mt-7 text-sm leading-7 text-slate-500 dark:text-slate-400">{isEnglish ? authoritySources.scopeNote : '公司與合作身分來源不等於特定型號的供貨、合規或商務承諾；這些項目仍須依型號文件與正式報價確認。'}</p></div></section>

    <section className="border-y border-slate-200 bg-slate-50 py-20 dark:border-slate-800 dark:bg-slate-900/60"><div className="mx-auto grid max-w-7xl gap-6 px-6 lg:grid-cols-3 lg:px-8">{capabilities.map(({ icon: Icon, title, body }) => <article key={tx(title, isEnglish)} className="rounded-2xl border border-slate-200 bg-white p-7 dark:border-slate-800 dark:bg-slate-950"><Icon className="h-7 w-7 text-cyan-600 dark:text-cyan-300" /><h2 className="mt-6 text-xl font-semibold">{tx(title, isEnglish)}</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{tx(body, isEnglish)}</p></article>)}</div></section>

    <section className="py-20"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2 lg:px-8"><div><h2 className="text-3xl font-bold">{isEnglish ? 'How EudTech works' : 'EudTech 的工作方式'}</h2><p className="mt-5 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'Before an implementation expands, EudTech writes down the objective, source, owner, approval point, acceptance criteria, and next action.' : 'EudTech 在擴大導入前，先寫清楚目標、來源、負責人、核准點、驗收條件與下一個行動。'}</p></div><CheckList isEnglish={isEnglish} items={[{ zh: '診斷：確認工作目標、使用者、資料與場地條件', en: 'Discovery: confirm objectives, users, data, and site conditions' }, { zh: '設計：建立範圍、來源、權限、核准點與驗收項目', en: 'Design: define scope, sources, permissions, approvals, and acceptance' }, { zh: '試點：用真實或去識別案例重跑完整流程', en: 'Pilot: replay the complete flow with real or de-identified cases' }, { zh: '上線：完成教育、文件、監測、維運與責任移交', en: 'Go live: complete training, documentation, monitoring, operations, and ownership handoff' }, { zh: '擴充：依事件資料與驗收結果決定下一個範圍', en: 'Expand: use event data and acceptance results to decide the next scope' }]} /></div></section>

    <section className="border-y border-slate-200 bg-slate-50 py-20 dark:border-slate-800 dark:bg-slate-900/60"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2 lg:px-8"><div><h2 className="text-3xl font-bold">{isEnglish ? 'Who EudTech serves' : '適合合作的組織'}</h2><p className="mt-5 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'The best fit is an organisation with a concrete operational, compute, or intelligence problem and an owner who can validate the result.' : '最適合的合作對象，是已有明確營運、運算或情報問題，且有負責人可以驗證結果的組織。'}</p></div><CheckList items={customers} isEnglish={isEnglish} /></div></section>

    <section className="bg-slate-950 py-16 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-7 px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><h2 className="text-3xl font-bold">{isEnglish ? 'Bring one concrete problem to the first conversation' : '第一次討論，帶一個具體問題即可'}</h2><p className="mt-3 max-w-2xl leading-7 text-slate-300">{isEnglish ? 'EudTech will help identify the data, systems, site conditions, owners, and acceptance criteria needed for the next step.' : 'EudTech 會協助確認下一步需要的資料、系統、場地條件、負責人與驗收標準。'}</p></div><ActionLink href="/contact">{isEnglish ? 'Contact EudTech' : '聯絡 EudTech'}</ActionLink></div></section>
  </PageShell>;
};
export default AboutPage;
