import React from 'react';
import { CheckCircle2, Network, ShieldCheck } from 'lucide-react';
import { useLanguageContext } from '../../contexts/LanguageContext';
import { ActionLink, CheckList, PageHero, PageShell } from './SitePagePrimitives';

const AboutPage: React.FC = () => {
  const { isEnglish } = useLanguageContext();
  return <PageShell title={{ zh: '關於 EudTech｜優達盟資訊科技', en: 'About EudTech' }} description={{ zh: '了解 EudTech 的公司定位、AI、運算基礎設施與社群情報能力。', en: 'Learn about EudTech positioning and capabilities across AI, infrastructure, and social intelligence.' }} path="/about">
    <PageHero eyebrow={{ zh: '關於 EudTech', en: 'About EudTech' }} title={{ zh: '把技術、流程與決策接在一起', en: 'Connect technology, operations, and decisions' }} lead={{ zh: '優達盟資訊科技有限公司協助企業、研究單位與公部門把 AI 軟體、運算設備與情報工具導入實際工作流程。', en: 'Eudaemonia Technology helps enterprises, research teams, and public institutions put AI software, compute systems, and intelligence tools into practical workflows.' }} isEnglish={isEnglish} actions={<ActionLink href="/contact">{isEnglish ? 'Work with EudTech' : '與 EudTech 合作'}</ActionLink>} />
    <section className="py-20"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-3 lg:px-8">{[[Network, { zh: '整合能力', en: 'Integration' }, { zh: '以 API、事件與權限邊界連接既有系統，保留資料與責任脈絡。', en: 'Connect existing systems through APIs, events, and permission boundaries while preserving context.' }], [ShieldCheck, { zh: '治理能力', en: 'Governance' }, { zh: '重要寄信、付款、刪除與狀態變更保留核准與稽核證據。', en: 'Keep approval and audit evidence for important sends, payments, deletion, and state changes.' }], [CheckCircle2, { zh: '交付能力', en: 'Delivery' }, { zh: '先做可操作的小範圍，再以實際資料、指標與事件擴大。', en: 'Start with an operable scope, then scale from real data, metrics, and events.' }]].map(([Icon, title, body]) => <article key={String(title)} className="rounded-2xl border border-slate-200 p-7 dark:border-slate-800"><Icon className="h-7 w-7 text-cyan-600 dark:text-cyan-300" /><h2 className="mt-6 text-xl font-semibold">{isEnglish ? (title as any).en : (title as any).zh}</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{isEnglish ? (body as any).en : (body as any).zh}</p></article>)}</div></section>
    <section className="bg-slate-50 py-20 dark:bg-slate-900/60"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2 lg:px-8"><div><h2 className="text-3xl font-bold">{isEnglish ? 'How we work' : 'EudTech 的工作方式'}</h2><p className="mt-5 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'We make the scope, evidence, owner, and next action explicit before technology is added.' : 'EudTech 在導入技術前先明確定義範圍、證據、負責人與下一個行動。'}</p></div><CheckList isEnglish={isEnglish} items={[{ zh: '先釐清工作目標與資料來源', en: 'Clarify goals and data sources first' }, { zh: '先選擇可量化的高價值流程', en: 'Choose a measurable high-value flow' }, { zh: '保留人工核准與可回溯證據', en: 'Keep human approval and traceable evidence' }, { zh: '以事件資料驗證後再擴大', en: 'Scale only after event data validates the result' }]} /></div></section>
  </PageShell>;
};
export default AboutPage;
