import React, { useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Cloud, Database, HardDrive, Layers3, Server, ShieldCheck, Sparkles } from 'lucide-react';
import { useLanguageContext } from '../../contexts/LanguageContext';
import { SITE_BOOKING } from '../../data/siteArchitecture';
import { PageShell } from './SitePagePrimitives';

const workloads = [
  { id: 'compute', icon: Server, label: ['運算與網站', 'Compute & hosting'], title: ['為網站與企業系統，規劃合適算力。', 'Right-size the cloud for your applications.'], description: ['從網站、API 到企業應用，依使用人數、流量與可用性需求，規劃運算資源與網路架構。', 'Plan compute and networking for websites, APIs, and business applications around traffic, users, and availability.'], services: ['Amazon EC2', 'AWS Lambda', 'Amazon VPC'], needs: ['使用人數、尖峰流量、作業系統與部署區域', 'Users, peak traffic, operating system, and deployment region'], output: ['架構建議、資源規格與用量估算', 'Architecture, resource sizing, and usage estimate'], href: 'https://aws.amazon.com/ec2/' },
  { id: 'storage', icon: HardDrive, label: ['儲存與備份', 'Storage & backup'], title: ['讓資料有地方放，也有復原計畫。', 'Give your data a home and a recovery plan.'], description: ['整理檔案、備份與封存需求，依資料量、存取頻率及保存時間，選擇儲存與備份方式。', 'Choose storage and backup options from your data volume, access frequency, retention needs, and recovery objectives.'], services: ['Amazon S3', 'AWS Backup'], needs: ['資料量、每月成長、保存期限與復原目標', 'Data volume, monthly growth, retention, and recovery targets'], output: ['儲存分層、備份範圍與費用估算', 'Storage tiers, backup scope, and cost estimate'], href: 'https://aws.amazon.com/s3/' },
  { id: 'database', icon: Database, label: ['資料庫與應用', 'Databases & apps'], title: ['把資料庫需求，接到下一階段成長。', 'Prepare your data platform for what comes next.'], description: ['依既有資料庫、交易量與停機容忍度，評估受管資料庫、應用串接及移轉步驟。', 'Evaluate managed databases, application integration, and migration steps against your engine, transaction volume, and downtime tolerance.'], services: ['Amazon RDS', 'Amazon Aurora', 'Amazon DynamoDB'], needs: ['資料庫引擎、容量、交易量與維護時段', 'Database engine, capacity, transaction volume, and maintenance window'], output: ['規格選型、移轉範圍與維運分工', 'Database sizing, migration scope, and operating responsibilities'], href: 'https://aws.amazon.com/rds/' },
  { id: 'ai', icon: Sparkles, label: ['生成式 AI', 'Generative AI'], title: ['先確認模型與用量，再規劃 AI 採購。', 'Start with the model, usage, and procurement path.'], description: ['以 Amazon Bedrock 評估企業知識查詢、文件處理與生成式 AI 應用，逐項確認模型、區域、資料要求與商用條件。', 'Evaluate enterprise knowledge search, document processing, and generative AI with Amazon Bedrock. Confirm models, regions, data requirements, and commercial terms for each project.'], services: ['Amazon Bedrock'], needs: ['應用目的、候選模型、用量與資料敏感程度', 'Use case, candidate models, expected usage, and data sensitivity'], output: ['可行性評估、模型條件與導入範圍', 'Feasibility, model eligibility, and implementation scope'], href: 'https://aws.amazon.com/bedrock/' },
];

const procurementFaqs = [
  { q: ['機關採購 AWS，規格至少要寫哪些交付？', 'What should an AWS procurement scope deliver?'], a: ['至少應寫明帳戶與 payer 歸屬、Organizations／IAM／MFA／KMS 管理、部署區域、架構與成本假設、RTO／RPO、備份還原測試、CloudTrail 與事件通報、責任矩陣、移交及終止時的匯出與刪除。各項內容依本案資料分級與服務範圍確認。', 'At minimum, define account and payer ownership, Organizations/IAM/MFA/KMS administration, regions, architecture and cost assumptions, RTO/RPO, restore tests, CloudTrail and incident notification, the responsibility matrix, handover, and export/deletion at exit. Confirm each item for the project’s data classification and service scope.'] },
  { q: ['AWS 用量費與導入服務如何分開？', 'How are AWS usage and implementation services separated?'], a: ['正式報價應分列 AWS 用量、AWS Support、導入或移轉服務、維運服務、稅與匯率假設；Savings Plans 或 Reserved Instances 等承諾用量也要另列期間、付款及使用假設。', 'A formal quote should separate AWS consumption, AWS Support, implementation or migration, managed support, tax, and exchange-rate assumptions. Any Savings Plans or Reserved Instances commitment should state its term, payment, and utilization assumptions separately.'] },
  { q: ['帳戶、root 與加密金鑰最後由誰掌握？', 'Who controls the account, root user, and encryption keys?'], a: ['應在建置前以書面確認客戶、EudTech 與其他供應商的角色。機關通常需要可移交的帳戶、身分、日誌與金鑰管理安排；任何代管權限都應有範圍、期限、稽核與撤銷方式。', 'Confirm customer, EudTech, and other supplier roles in writing before deployment. A public-sector customer normally needs transferable arrangements for accounts, identities, logs, and key management. Any delegated administration should have scope, duration, audit, and revocation terms.'] },
  { q: ['備份存在，就代表災難復原可驗收嗎？', 'Does having backups prove disaster recovery?'], a: ['不代表。要先定義 RTO、RPO、備份範圍、保存與跨區策略，再用還原演練證明資料與服務能在約定時間內恢復；測試結果、例外與責任人都應留下紀錄。', 'No. Define RTO, RPO, backup scope, retention, and cross-region strategy, then use restore exercises to show that data and services recover within the agreed target. Record results, exceptions, and owners.'] },
  { q: ['EudTech 是否自稱 AWS reseller 或 APN 夥伴？', 'Does EudTech claim AWS reseller or APN partner status?'], a: ['本頁不以未公開驗證的夥伴資格作為採購依據。EudTech 的實際商業角色、計費方、帳戶安排、可供服務及支援範圍，均在正式報價與合約中逐項確認。', 'This page does not rely on unverified public partner status. EudTech’s commercial role, billing party, account arrangement, available services, and support scope are confirmed item by item in the formal quote and contract.'] }
] as const;

const AwsCloudSolutionPage: React.FC = () => {
  const { isEnglish } = useLanguageContext();
  const [selected, setSelected] = useState('compute');
  const t = (pair: string[]) => pair[isEnglish ? 1 : 0];
  const active = workloads.find(item => item.id === selected)!;
  const inquiry = (topic = '') => `mailto:quote@eudaemonia.tech?subject=${encodeURIComponent(`${isEnglish ? 'AWS cloud sales enquiry' : 'AWS 雲端銷售詢價'}${topic ? `｜${topic}` : ''}`)}&body=${encodeURIComponent(isEnglish ? 'Company:\nWorkload / AWS services:\nExisting AWS account (yes/no):\nEstimated usage / budget:\nTarget launch date:\n' : '公司名稱：\n用途／AWS 服務需求：\n是否已有 AWS 帳戶：\n預估用量／預算：\n預計上線時間：\n')}`;
  const button = 'inline-flex min-h-12 items-center justify-center gap-3 rounded-lg bg-orange-400 px-6 py-3.5 text-sm font-bold text-slate-950 transition hover:bg-orange-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-500 focus-visible:ring-offset-4';
  return <PageShell title={{ zh: 'AWS 雲端銷售服務｜選型、報價與導入', en: 'AWS Cloud Sales, Quotes & Deployment' }} description={{ zh: 'EudTech 協助企業規劃 AWS 運算、儲存、資料庫與生成式 AI，整合需求評估、採購報價、導入與維運範圍。', en: 'Plan AWS compute, storage, databases, and generative AI with EudTech, from requirements and quotes to deployment and support scope.' }} path="/solutions/aws" structuredData={[
    { '@context': 'https://schema.org', '@type': 'Service', name: isEnglish ? 'AWS cloud sales services' : 'AWS 雲端銷售服務', serviceType: isEnglish ? 'Cloud procurement planning and implementation' : '雲端採購規劃與導入', provider: { '@id': 'https://eudaemonia.tech/#organization' }, areaServed: { '@type': 'Country', name: 'Taiwan' }, url: 'https://eudaemonia.tech/solutions/aws/' },
    { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: procurementFaqs.map(item => ({ '@type': 'Question', name: t(item.q), acceptedAnswer: { '@type': 'Answer', text: t(item.a) } })) }
  ]}>
    <section className="relative overflow-hidden bg-[#101a2b] pb-16 pt-32 text-white sm:pb-20 lg:pt-40">
      <div aria-hidden="true" className="pointer-events-none absolute inset-0 opacity-[0.05]" style={{ backgroundImage: 'linear-gradient(#fff 1px, transparent 1px), linear-gradient(90deg, #fff 1px, transparent 1px)', backgroundSize: '56px 56px' }} />
      <div className="relative mx-auto grid max-w-7xl items-center gap-12 px-6 lg:grid-cols-[1.15fr_0.85fr] lg:gap-14 lg:px-8">
        <div>
          <p className="flex items-center gap-3 text-xs font-bold uppercase tracking-[0.18em] text-orange-300"><span className="h-px w-8 bg-orange-400" />EudTech / AWS Cloud Sales</p>
          <p className="mt-8 text-lg font-semibold text-slate-300">{isEnglish ? 'AWS cloud sales services' : 'AWS 雲端銷售服務'}</p>
          <h1 className="mt-4 text-4xl font-bold leading-[1.2] tracking-tight sm:text-5xl xl:text-6xl">{isEnglish ? 'AWS cloud planning and quotes,' : 'AWS 雲端選型與報價，'}<span className="mt-2 block text-orange-300">{isEnglish ? 'deployment and operations.' : '導入與維運。'}</span></h1>
          <p className="mt-7 max-w-xl text-base leading-8 text-slate-300 sm:text-lg">{isEnglish ? 'From choosing services to planning your budget and launch. One EudTech contact helps turn your cloud requirements into a clear procurement and deployment plan.' : '從服務選型、預算估算到採購與上線，由 EudTech 台灣窗口整合需求，讓每一筆雲端投資都有清楚的下一步。'}</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row">
            <a href={inquiry()} className={`${button} focus-visible:ring-offset-slate-900`}>{isEnglish ? 'Discuss an AWS quote' : '洽詢 AWS 報價'}<ArrowUpRight size={18} aria-hidden="true" /></a>
            <a href="#aws-services" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-lg border border-slate-500 px-6 py-3.5 text-sm font-semibold hover:border-orange-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-400">{isEnglish ? 'Explore services' : '看看適合的服務'}<ArrowDown size={16} aria-hidden="true" /></a>
          </div>
          <p className="mt-5 text-xs leading-6 text-slate-400">{isEnglish ? 'Service availability, billing, and activation are confirmed in your formal quote.' : '可供服務、計費條件及開通時程，依正式報價確認。'}</p>
          <p className="mt-2 text-xs leading-6 text-slate-400">{isEnglish ? 'Content reviewed: 2026-10-04' : '內容最後檢閱：2026-10-04'}</p>
        </div>
        <div className="relative rounded-3xl border border-white/15 bg-[#17243a] p-6 shadow-2xl sm:p-8" aria-label={isEnglish ? 'AWS procurement planning overview' : 'AWS 採購規劃示意'}>
          <div className="flex items-center justify-between border-b border-white/10 pb-5"><span className="text-xs font-semibold tracking-[0.16em] text-slate-400">{isEnglish ? 'YOUR CLOUD FOUNDATION' : '企業雲端基礎'}</span><Cloud className="text-orange-300" size={28} aria-hidden="true" /></div>
          <div className="py-8"><span className="text-6xl font-bold tracking-tight">AWS</span><p className="mt-3 text-sm text-slate-300">Amazon Web Services</p></div>
          <div className="grid grid-cols-2 gap-3">{workloads.map(({ id, icon: Icon, label, services }) => <div key={id} className="rounded-xl border border-white/10 bg-white/[0.04] p-4"><Icon size={21} className="text-orange-300" aria-hidden="true" /><p className="mt-4 text-sm font-semibold">{t(label)}</p><p className="mt-1 text-[11px] leading-5 text-slate-400">{services[0]}</p></div>)}</div>
          <div className="mt-6 flex items-center gap-3 border-t border-white/10 pt-5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-orange-400 text-slate-950"><ArrowRight size={18} aria-hidden="true" /></span><p className="text-sm leading-6 text-slate-300">{isEnglish ? 'Requirements → Quote → Deployment' : '釐清需求 → 確認報價 → 安排導入'}</p></div>
        </div>
      </div>
    </section>
    <div className="border-b border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto grid max-w-7xl gap-5 px-6 py-6 sm:grid-cols-3 lg:px-8">{[[Cloud, ['依工作負載選型', 'Workload-led planning']], [Layers3, ['整合採購與導入', 'Procurement through deployment']], [ShieldCheck, ['清楚的費用與責任', 'Clear costs and responsibilities']]].map(([Icon, label], index) => { const FeatureIcon = Icon as typeof Cloud; return <div key={index} className="flex items-center gap-3 text-sm font-medium"><FeatureIcon size={19} className="shrink-0 text-orange-600 dark:text-orange-300" aria-hidden="true" />{t(label as string[])}</div>; })}</div></div>
    <section id="aws-services" className="scroll-mt-24 py-16 sm:py-24">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-700 dark:text-orange-300">{isEnglish ? '01 / Choose your workload' : '01／從用途選服務'}</p>
        <h2 className="mt-4 text-3xl font-bold leading-tight tracking-tight sm:text-4xl">{isEnglish ? 'What would you like to run on AWS?' : '你想用 AWS 做什麼？'}</h2>
        <p className="mt-5 max-w-2xl leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'Start with a business need. We help identify suitable services and the information needed for a useful quote.' : '不用先背熟服務名稱。從實際用途開始，整理適合的服務組合與詢價條件。'}</p>
        <div className="mt-9 grid grid-cols-2 gap-2 md:grid-cols-4" aria-label={isEnglish ? 'Workload options' : '工作負載選項'}>{workloads.map(({ id, icon: Icon, label }) => <button key={id} type="button" aria-pressed={selected === id} aria-controls="aws-workload-details" onClick={() => setSelected(id)} className={`flex min-h-14 items-center justify-center gap-2 rounded-lg border px-3 py-3 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-500 focus-visible:ring-offset-2 ${selected === id ? 'border-slate-900 bg-slate-900 text-white dark:border-orange-300 dark:bg-orange-300 dark:text-slate-950' : 'border-slate-200 bg-white text-slate-600 hover:border-orange-400 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300'}`}><Icon size={18} className="shrink-0" aria-hidden="true" />{t(label)}</button>)}</div>
        <div id="aws-workload-details" className="mt-5 grid overflow-hidden rounded-2xl border border-slate-200 dark:border-slate-800 lg:grid-cols-[1.3fr_0.7fr]" aria-live="polite">
          <div className="p-7 sm:p-10"><h3 className="max-w-2xl text-2xl font-semibold leading-snug sm:text-3xl">{t(active.title)}</h3><p className="mt-5 max-w-2xl leading-8 text-slate-600 dark:text-slate-300">{t(active.description)}</p><div className="mt-7 flex flex-wrap gap-2">{active.services.map(service => <span key={service} className="rounded-md bg-slate-100 px-3 py-2 font-mono text-xs text-slate-700 dark:bg-slate-800 dark:text-slate-200">{service}</span>)}</div>{selected === 'ai' && <p className="mt-5 text-sm leading-7 text-slate-600 dark:text-slate-300">{isEnglish ? 'Model availability, regions, and procurement eligibility are confirmed for each project.' : '依專案逐項確認可用模型、部署區域與採購資格。'}</p>}<a href={active.href} target="_blank" rel="noreferrer" className="mt-7 inline-flex min-h-11 items-center gap-2 text-sm font-semibold underline underline-offset-4 hover:text-orange-600">{isEnglish ? 'View AWS service information' : '查看 AWS 原廠服務介紹'}<ArrowUpRight size={16} aria-hidden="true" /></a></div>
          <div className="flex flex-col bg-slate-50 p-7 dark:bg-slate-900 sm:p-10"><p className="text-xs font-semibold tracking-wider text-orange-700 dark:text-orange-300">{isEnglish ? 'FOR YOUR QUOTE' : '報價前一起確認'}</p><p className="mt-4 text-sm leading-7">{t(active.needs)}</p><p className="mt-6 text-xs font-semibold tracking-wider text-slate-500 dark:text-slate-400">{isEnglish ? 'WHAT WE PLAN' : 'EudTech 協助整理'}</p><p className="mt-3 text-sm leading-7">{t(active.output)}</p><a href={inquiry(t(active.label))} className={`${button} mt-8`}>{isEnglish ? 'Enquire about this service' : '洽詢這項服務'}<ArrowRight size={16} aria-hidden="true" /></a></div>
        </div>
        <section className="mt-10" aria-labelledby="aws-all-workloads-heading">
          <h3 id="aws-all-workloads-heading" className="text-xl font-semibold">{isEnglish ? 'All workload planning answers' : '四類工作負載的完整規劃摘要'}</h3>
          <p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600 dark:text-slate-300">{isEnglish ? 'Open any item to review the inputs, expected output, and official AWS service source. These summaries remain available in the initial page content.' : '展開任一項，即可核對詢價輸入、規劃輸出與 AWS 原廠來源；以下內容均包含在頁面初始文字中。'}</p>
          <div className="mt-5 grid gap-4 md:grid-cols-2">{workloads.map(item => <details key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><summary className="cursor-pointer font-semibold">{t(item.label)} · {t(item.title)}</summary><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">{t(item.description)}</p><p className="mt-3 text-sm"><strong>{isEnglish ? 'Quote inputs: ' : '詢價輸入：'}</strong>{t(item.needs)}</p><p className="mt-2 text-sm"><strong>{isEnglish ? 'Planned output: ' : '規劃輸出：'}</strong>{t(item.output)}</p><p className="mt-2 text-sm"><strong>{isEnglish ? 'Services: ' : '服務：'}</strong>{item.services.join(' · ')}</p><a href={item.href} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold underline underline-offset-4">{isEnglish ? 'Official AWS service information' : 'AWS 原廠服務資料'}<ArrowUpRight size={15} aria-hidden="true" /></a></details>)}</div>
        </section>
      </div>
    </section>
    <section className="border-y border-slate-200 bg-slate-50 py-16 dark:border-slate-800 dark:bg-slate-900/50 sm:py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-700 dark:text-orange-300">{isEnglish ? '02 / One coordinated plan' : '02／把採購與交付接起來'}</p><h2 className="mt-4 text-3xl font-bold leading-tight tracking-tight sm:text-4xl">{isEnglish ? 'A clear scope before you commit.' : '採購前，先把每一件事說清楚。'}</h2></div><p className="max-w-xl leading-8 text-slate-600 dark:text-slate-300 lg:pt-7">{isEnglish ? 'Cloud consumption and professional services have different costs and responsibilities. Your proposal makes both visible, so you can decide with confidence.' : '雲端用量與專業服務分項規劃。從每月預算、帳戶安排到誰負責維運，都在報價與服務範圍中確認。'}</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[
          { n: 'A', title: ['選型與採購', 'Planning & procurement'], body: ['確認服務、區域、資源規格與用量，整理正式報價所需條件。', 'Define services, regions, resource sizing, and usage for a formal quote.'], points: [['服務清單與預算假設', 'Service list and budget assumptions'], ['計費、稅務與授權條件', 'Billing, tax, and licensing terms']] },
          { n: 'B', title: ['建置與移轉', 'Deployment & migration'], body: ['依約定範圍規劃帳戶、網路、權限及資料移轉，確認上線與驗收步驟。', 'Plan accounts, networking, access, and migration within an agreed deployment and acceptance scope.'], points: [['架構與建置範圍', 'Architecture and deployment scope'], ['時程、測試與交接文件', 'Schedule, tests, and handover']] },
          { n: 'C', title: ['維運與費用檢視', 'Operations & cost review'], body: ['約定日常維護、事件處理與費用檢視方式，讓上線後的工作有明確負責人。', 'Agree maintenance, incident handling, and cost reviews with clearly assigned owners.'], points: [['支援時段與服務責任', 'Support hours and responsibilities'], ['用量檢視與資源調整建議', 'Usage review and sizing advice']] },
        ].map(({ n, title, body, points }) => <article key={n} className="rounded-2xl border border-slate-200 bg-white p-7 dark:border-slate-700 dark:bg-slate-900"><span className="font-mono text-sm text-orange-700 dark:text-orange-300">/{n}</span><h3 className="mt-5 text-xl font-semibold">{t(title)}</h3><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">{t(body)}</p><ul className="mt-6 space-y-3 border-t border-slate-100 pt-5 dark:border-slate-800">{points.map(point => <li key={point[1]} className="flex gap-2 text-sm leading-6"><Check size={17} className="mt-0.5 shrink-0 text-orange-600 dark:text-orange-300" aria-hidden="true" />{t(point)}</li>)}</ul></article>)}</div></div></section>
    <section className="py-16 sm:py-24" aria-labelledby="aws-procurement-faq"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-[0.65fr_1.35fr] lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-700 dark:text-orange-300">{isEnglish ? 'PROCUREMENT FAQ' : '機關與企業採購問答'}</p><h2 id="aws-procurement-faq" className="mt-4 text-3xl font-bold">{isEnglish ? 'Define ownership before deployment.' : '上線前，先寫清楚帳戶、費用與責任。'}</h2><div className="mt-6 space-y-3 text-sm"><a className="block font-semibold underline underline-offset-4" href="https://aws.amazon.com/compliance/shared-responsibility-model/" target="_blank" rel="noreferrer">AWS Shared Responsibility Model</a><a className="block font-semibold underline underline-offset-4" href="https://docs.aws.amazon.com/wellarchitected/latest/framework/the-pillars-of-the-framework.html" target="_blank" rel="noreferrer">AWS Well-Architected Framework</a><a className="block font-semibold underline underline-offset-4" href="https://calculator.aws/" target="_blank" rel="noreferrer">AWS Pricing Calculator</a></div></div><div className="space-y-3">{procurementFaqs.map(item => <details key={item.q[1]} className="rounded-2xl border border-slate-200 p-5 dark:border-slate-800"><summary className="cursor-pointer font-semibold">{t(item.q)}</summary><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">{t(item.a)}</p></details>)}</div></div></section>
    <section className="py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-[0.7fr_1.3fr] lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-700 dark:text-orange-300">{isEnglish ? '03 / Getting started' : '03／開始合作'}</p><h2 className="mt-4 text-3xl font-bold leading-tight tracking-tight">{isEnglish ? 'From a need to a launch plan.' : '從一個需求，走到上線計畫。'}</h2></div><ol className="space-y-0">{[
      [['說明用途與預算', 'Share your needs'], ['提供現有環境、預估用量及目標時程，由 EudTech 整理需求。', 'We review your environment, expected usage, budget, and target date.']],
      [['確認方案與報價', 'Review the proposal'], ['確認可供服務、採購管道、計費方式及導入範圍，取得書面方案。', 'Confirm service availability, procurement route, billing, and implementation scope in writing.']],
      [['安排開通與交付', 'Plan activation and handover'], ['完成商務條件確認後，依核定範圍安排開通、建置、測試與交接。', 'Once commercial terms are agreed, schedule activation, setup, testing, and handover.']],
    ].map(([title, body], i) => <li key={i} className="flex gap-5 border-t border-slate-200 py-6 dark:border-slate-800"><span className="pt-1 font-mono text-sm text-orange-700 dark:text-orange-300">0{i + 1}</span><div><h3 className="text-lg font-semibold">{t(title)}</h3><p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">{t(body)}</p></div></li>)}</ol></div></section>
    <section className="px-6 pb-20 lg:px-8"><div className="mx-auto max-w-7xl rounded-3xl bg-[#101a2b] p-8 text-white sm:p-12"><div className="grid items-center gap-8 lg:grid-cols-[1.3fr_0.7fr]"><div><p className="text-xs font-semibold tracking-[0.18em] text-orange-300">LET’S PLAN YOUR CLOUD</p><h2 className="mt-4 text-3xl font-bold leading-tight">{isEnglish ? 'Tell us what you want to put on AWS.' : '把你的雲端需求，交給 EudTech。'}</h2><p className="mt-4 max-w-xl leading-8 text-slate-300">{isEnglish ? 'Bring a new project or an existing AWS environment. We will help clarify the services, budget, and next step.' : '無論是新專案或既有 AWS 環境，我們一起確認服務組合、預算與下一步。'}</p></div><div className="flex flex-col gap-3"><a href={inquiry()} className={button}>{isEnglish ? 'Request AWS sales consultation' : '洽詢 AWS 銷售服務'}<ArrowUpRight size={18} aria-hidden="true" /></a><a href={SITE_BOOKING.href} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg border border-slate-500 px-5 py-3 text-sm font-semibold hover:border-orange-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-400">{isEnglish ? 'Book a consultation' : '預約線上諮詢'}<ArrowUpRight size={16} aria-hidden="true" /></a></div></div></div></section>
  </PageShell>;
};

export default AwsCloudSolutionPage;
