import React from 'react';
import { Bot, CheckCircle2, ClipboardList, Cpu, MailCheck, MessagesSquare, Radar, Route } from 'lucide-react';
import { useLanguageContext } from '../../contexts/LanguageContext';
import { ActionLink, PageHero, PageShell } from './SitePagePrimitives';
import ContactSection from '../contact/ContactSection';

const ContactPage: React.FC = () => {
  const { isEnglish } = useLanguageContext();
  const needs = [
    { icon: Bot, title: { zh: 'AI Agent 與 Headless SaaS', en: 'AI agents & headless SaaS' }, body: { zh: '串接既有系統，建立品牌入口、事件流程、AI Agent、權限與治理。', en: 'Connect existing systems and build branded portals, event workflows, AI agents, permissions, and governance.' } },
    { icon: Cpu, title: { zh: 'AI 運算設備', en: 'AI infrastructure' }, body: { zh: 'GPU 伺服器、工作站與液冷系統的配置與正式報價。', en: 'Configuration and formal quotes for GPU servers, workstations, and liquid cooling.' } },
    { icon: Radar, title: { zh: '社群情報', en: 'Social intelligence' }, body: { zh: 'Cyabra 品牌保護、假資訊與社群風險分析。', en: 'Cyabra brand protection, disinformation, and social risk analysis.' } }
  ];
  return <PageShell title={{ zh: '聯絡 EudTech｜開始諮詢', en: 'Contact EudTech' }} description={{ zh: '選擇企業 AI Agent 與 Headless SaaS、AI 運算設備或社群情報需求，與 EudTech 安排下一步。', en: 'Choose an enterprise AI agent and headless SaaS, AI infrastructure, or social intelligence need and arrange the next step with EudTech.' }} path="/contact">
    <PageHero eyebrow={{ zh: '聯絡與諮詢', en: 'Contact' }} title={{ zh: '先說明需求，再安排正確的下一步', en: 'Start with the need, then choose the right next step' }} lead={{ zh: '選擇需求類型後，用 Email 或 Microsoft Bookings 安排會議。會議討論範圍、資料、時程、授權與驗收指標。', en: 'Choose a need, then book a meeting by email or through Microsoft Bookings. The meeting covers scope, data, timing, licensing, and acceptance metrics.' }} isEnglish={isEnglish} image="/brand-provenance/eudtech-brand-consultation.webp" imageAlt={{ zh: 'EudTech 諮詢、需求確認與下一步安排的品牌情境圖', en: 'Brand scene for EudTech consultation, discovery, and next-step planning' }} imagePosition="center" actions={<ActionLink href="#contact-options">{isEnglish ? 'View contact options' : '查看聯絡方式'}</ActionLink>} />
    <section className="py-16"><div className="mx-auto grid max-w-7xl gap-5 px-6 md:grid-cols-3 lg:px-8">{needs.map(({ icon: Icon, title, body }) => <a key={title.zh} href="#contact-options" className="rounded-2xl border border-slate-200 p-6 transition hover:border-cyan-400 dark:border-slate-800"><Icon className="h-6 w-6 text-cyan-600 dark:text-cyan-300" /><h2 className="mt-5 font-semibold">{isEnglish ? title.en : title.zh}</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{isEnglish ? body.en : body.zh}</p></a>)}</div></section>
    <section className="border-y border-slate-200 bg-slate-50 py-16 dark:border-slate-800 dark:bg-slate-900/60"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2 lg:px-8"><div><ClipboardList className="h-7 w-7 text-cyan-600 dark:text-cyan-300" /><h2 className="mt-5 text-2xl font-bold">{isEnglish ? 'Information to bring' : '討論前可準備的資料'}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-slate-600 dark:text-slate-300"><li>• {isEnglish ? 'The current problem, workflow, or workload' : '目前要處理的問題、流程或工作負載'}</li><li>• {isEnglish ? 'Existing systems, hardware, licences, and data sources' : '既有系統、設備、授權與資料來源'}</li><li>• {isEnglish ? 'Users, owners, site conditions, timing, and budget range' : '使用者、負責人、場地條件、預定時程與預算範圍'}</li><li>• {isEnglish ? 'A result that the team can accept or measure' : '團隊可以驗收或量測的成果'}</li></ul></div><div><CheckCircle2 className="h-7 w-7 text-cyan-600 dark:text-cyan-300" /><h2 className="mt-5 text-2xl font-bold">{isEnglish ? 'What the first conversation produces' : '第一次討論會確認的結果'}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-slate-600 dark:text-slate-300"><li>• {isEnglish ? 'Whether the need fits EudTech and the relevant solution line' : '需求是否符合 EudTech 服務與適用的解決方案'}</li><li>• {isEnglish ? 'Missing data, permissions, technical details, or site conditions' : '尚缺的資料、權限、技術細節或場地條件'}</li><li>• {isEnglish ? 'The next deliverable: discovery, pilot, configuration, demo, or quote' : '下一份交付：診斷、試點、配置、示範或正式報價'}</li><li>• {isEnglish ? 'The owner and evidence required to validate the next step' : '負責人與下一步需要的驗證證據'}</li></ul></div></div></section>
    <section className="py-16"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">{isEnglish ? 'What happens next' : '送出需求後的流程'}</p><h2 className="mt-4 text-3xl font-bold">{isEnglish ? 'Three steps from first contact to a written next step' : '從聯絡到下一步，只有三個步驟'}</h2><p className="mt-4 leading-7 text-slate-600 dark:text-slate-300">{isEnglish ? 'The EudTech contact is Frank Hsu. Business-day enquiries are reviewed and routed to the relevant solution line.' : 'EudTech 聯絡窗口為 Frank Hsu。工作日收到需求後，EudTech 會依需求類型確認並安排對應方案。'}</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[
      { icon: MailCheck, n: '01', title: isEnglish ? 'Request received' : '收到需求', body: isEnglish ? 'EudTech records the company, need, preferred contact route, and source.' : 'EudTech 記錄公司、需求、偏好聯絡方式與來源。' },
      { icon: MessagesSquare, n: '02', title: isEnglish ? 'Scope confirmation' : '確認範圍', body: isEnglish ? 'Frank confirms the objective, current environment, owner, timing, and missing information.' : 'Frank 確認目標、現況、負責人、時程與尚缺資料。' },
      { icon: Route, n: '03', title: isEnglish ? 'Written next step' : '取得下一步', body: isEnglish ? 'You receive a written proposal for the next step: discovery, pilot, configuration, demo, or quote.' : '客戶會收到書面的下一步建議：診斷、試點、配置、示範或正式報價。' }
    ].map(({ icon: Icon, n, title, body }) => <article key={n} className="rounded-2xl border border-slate-200 p-6 dark:border-slate-800"><div className="flex items-center justify-between"><Icon className="h-6 w-6 text-cyan-600 dark:text-cyan-300" /><span className="text-sm font-semibold text-cyan-700 dark:text-cyan-300">{n}</span></div><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{body}</p></article>)}</div></div></section>
    <div id="contact-options" className="scroll-mt-20"><ContactSection /></div>
  </PageShell>;
};
export default ContactPage;
