import React, { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Download, ShieldCheck } from 'lucide-react';
import { useLanguageContext } from '../../contexts/LanguageContext';
import { SITE_BOOKING } from '../../data/siteArchitecture';
import { pqcExperts, pqcPhases, pqcScenarios, PqcText } from '../../data/pqcAdvisory';
import { PageShell } from './SitePagePrimitives';
import ServiceFaqList from './ServiceFaqList';
import { serviceQuestionsSchema } from '../../utils/seo/serviceQuestions';
import './PqcAdvisoryPage.css';

const PqcAdvisoryPage: React.FC = () => {
  const { isEnglish } = useLanguageContext();
  const t = (pair: PqcText) => pair[isEnglish ? 1 : 0];
  const [phase, setPhase] = useState(0);
  const [scenario, setScenario] = useState(0);
  const [answers, setAnswers] = useState({ inventory: '', focus: '', lifetime: '' });
  const [attempted, setAttempted] = useState(false);
  const [showResult, setShowResult] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const resultRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (showResult) resultRef.current?.focus(); }, [showResult]);
  const activePhase = pqcPhases[phase], activeScenario = pqcScenarios[scenario];
  const fields = [
    { id: 'inventory', label: ['目前掌握密碼資產的程度？', 'How complete is your cryptographic inventory?'], options: [['unknown', '還沒有完整清單／不確定', 'No complete list / unsure'], ['partial', '已有部分清單', 'Partial inventory'], ['mapped', '已有清單與系統擁有者', 'Inventory and system owners identified']] },
    { id: 'focus', label: ['最想先處理的場景？', 'Which scenario should come first?'], options: [['tls', '網站、API 或服務間連線', 'Websites, APIs, or service connections'], ['signing', '軟體、韌體或文件簽章', 'Software, firmware, or document signing'], ['vendor', '設備、PKI 或供應商依賴', 'Devices, PKI, or vendor dependencies']] },
    { id: 'lifetime', label: ['相關資料需要保密多久？', 'How long must the data remain confidential?'], options: [['short', '以短期為主（5 年以內）', 'Mainly short term (up to 5 years)'], ['long', '有長期機密（超過 5 年）', 'Long-term confidentiality (over 5 years)'], ['unknown', '還需要確認', 'Needs clarification']] }
  ] as const;
  const ready = answers.inventory === 'mapped';
  const selectedScenario = pqcScenarios.find(s => s.id === answers.focus) || pqcScenarios[0];
  const resultTitle: PqcText = ready ? answers.focus === 'vendor' ? ['先確認供應商支援與升級路徑', 'Confirm vendor support and upgrade paths first'] : ['從一個可回復的試點開始', 'Start with a reversible pilot'] : ['從盤點與路線圖開始', 'Start with inventory and a roadmap'];
  const resultDescription: PqcText = ready ? ['確認清單品質、系統擁有者、產品支援與測試環境，再定義通過及回復條件。', 'Confirm inventory quality, system ownership, product support, and a test environment, then set acceptance and rollback criteria.'] : ['整理密碼使用位置、版本、擁有者與相依關係，註記未知範圍，再決定試點。', 'Map cryptographic use, versions, owners, and dependencies. Record unknowns before selecting a pilot.'];
  const lifetimeNote: PqcText = answers.lifetime === 'long' ? ['將保密年限、傳輸暴露與遷移前置時間納入優先順序。', 'Prioritize confidentiality duration, transmission exposure, and migration lead time.'] : answers.lifetime === 'unknown' ? ['先與資料擁有者確認保密年限；未知不代表低風險。', 'Clarify confidentiality duration with data owners. Unknown does not mean low risk.'] : ['仍需評估簽章、身分驗證、服務重要性與供應商生命週期。', 'Still assess signatures, authentication, service criticality, and vendor lifecycles.'];
  const limitation: PqcText = ['此結果僅依自填答案作初步分流，未掃描系統，非風險評級、正式報價或已成立的服務委託。', 'This is initial guidance from your answers. No systems were scanned; it is not a risk rating, formal quote, or service engagement.'];
  const submit = (e: React.FormEvent) => {
    e.preventDefault(); setAttempted(true); setDownloaded(false);
    const missing = fields.find(f => !answers[f.id]);
    if (missing) { setShowResult(false); document.getElementById(`pqc-${missing.id}`)?.focus(); return; }
    setShowResult(true);
  };
  const download = () => {
    const summary = [t(['EudTech PQC 導入範圍摘要', 'EudTech PQC advisory scope']), '', ...fields.map(f => `${t(f.label)} ${f.options.find(o => o[0] === answers[f.id])?.[isEnglish ? 2 : 1]}`), '', t(resultTitle), t(resultDescription), t(selectedScenario.check), t(lifetimeNote), '', t(limitation)].join('\n');
    const url = URL.createObjectURL(new Blob(['\ufeff', summary], { type: 'text/plain;charset=utf-8' }));
    const link = document.createElement('a'); link.href = url; link.download = 'eudtech-pqc-advisory-scope.txt'; document.body.append(link); link.click(); link.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000); setDownloaded(true);
  };
  const structuredData = [
    { '@context': 'https://schema.org', '@type': 'Service', '@id': 'https://eudaemonia.tech/solutions/pqc/#service', name: t(['PQC 後量子密碼遷移顧問', 'Post-quantum cryptography migration advisory']), serviceType: t(['密碼資產盤點、架構試點與遷移治理', 'Cryptographic inventory, architecture pilots, and migration governance']), provider: { '@id': 'https://eudaemonia.tech/#organization' }, areaServed: { '@type': 'Country', name: 'Taiwan' }, url: 'https://eudaemonia.tech/solutions/pqc/' },
    serviceQuestionsSchema('pqc', isEnglish),
    { '@context': 'https://schema.org', '@type': 'Person', name: 'Hung-Jr Shiu', alternateName: '許宏誌', jobTitle: t(['國立臺北大學資訊工程學系助理教授', 'Assistant Professor, Computer Science and Information Engineering']), affiliation: { '@type': 'CollegeOrUniversity', name: t(['國立臺北大學', 'National Taipei University']) }, url: 'https://scholar.ntpu.edu.tw/en/persons/hung-jr-shiu/', image: 'https://eudaemonia.tech/vendor/pqc/home-hung-jr-shiu.webp', knowsAbout: ['Cryptography', 'Algorithms', 'Post-quantum cryptography', 'Steganography', 'Multimedia security'] }
  ];
  return <PageShell path="/solutions/pqc" title={{ zh: 'PQC 後量子密碼導入與專家顧問', en: 'PQC Migration & Expert Advisory' }} description={{ zh: '以密碼學研究與工程判斷，規劃密碼資產盤點、PQC 架構試點及分階段遷移。認識 EudTech 專家團隊與研究依據。', en: 'Meet the experts guiding cryptographic inventories, PQC architecture pilots and phased migration, backed by academic and ML-DSA implementation research.' }} structuredData={structuredData}>
    <div className="pqc-page">
      <section className="pqc-hero">
        <div className="pqc-container pqc-hero-grid">
          <div><p className="pqc-eyebrow">POST-QUANTUM CRYPTOGRAPHY / ADVISORY</p><h1>{t(['PQC 後量子密碼遷移：盤點、試點與治理', 'PQC migration: inventory, pilots, and governance'])}</h1><p className="pqc-hero-subtitle">{t(['PQC 後量子密碼導入服務', 'Post-quantum cryptography migration'])}</p><p className="pqc-lead">{t(['從威脅模型與密碼資產盤點，到架構與試點驗證。將後量子密碼標準，轉成可執行的導入決策。', 'From threat models and cryptographic inventories to architecture and pilot validation. Turn post-quantum standards into actionable migration decisions.'])}</p><p className="pqc-fine">{t(['內容最後檢閱：2026-10-04', 'Content reviewed: 2026-10-04'])}</p><div className="pqc-actions"><a href="#pqc-start" className="pqc-button">{t(['找到導入起點', 'Find your starting point'])}<ArrowRight aria-hidden="true" size={18}/></a><a href="#pqc-team" className="pqc-text-link">{t(['認識專家團隊', 'Meet the experts'])}<ArrowDown aria-hidden="true" size={16}/></a></div></div>
          <aside className="pqc-expert-panel" aria-label={t(['專家研究背景', 'Expert research backgrounds'])}><p className="pqc-eyebrow">THE PEOPLE BEHIND THE ADVICE</p>{pqcExperts.map(expert => <a key={expert.id} href={`#${expert.id}`} className="pqc-hero-expert"><img src={expert.image} width="240" height="240" alt={expert.name} decoding="async" sizes="(max-width: 767px) 90px, 76px"/><div><h2>{expert.name}</h2><p>{t(expert.focus)}</p><span>{t(expert.degree)}</span></div></a>)}<a href="#pqc-research" className="pqc-research-link"><span>FIPS 204 / ML-DSA</span><strong>{t(['後量子數位簽章實作研究', 'Post-quantum signature implementation research'])}</strong><ArrowUpRight aria-hidden="true" size={20}/></a></aside>
        </div>
      </section>
      <section className="pqc-container pqc-section" id="pqc-team" aria-labelledby="pqc-team-heading"><p className="pqc-eyebrow">01 / EXPERT TEAM</p><div className="pqc-section-heading"><h2 id="pqc-team-heading">{t(['密碼學研究背景，支撐導入決策。', 'Research depth. Practical judgment.'])}</h2><p>{t(['從研究專長、學術背景到公開成果，認識提供技術判斷的專家。', 'Meet the people through their expertise, academic backgrounds, and public research.'])}</p></div><div className="pqc-team-grid">{pqcExperts.map(expert => <article className="pqc-card pqc-expert-card" id={expert.id} key={expert.id}><div className="pqc-profile"><img src={expert.image} alt={expert.name} width="240" height="240" loading="lazy" decoding="async" sizes="(max-width: 767px) 90px, 76px"/><div><p className="pqc-eyebrow">{t(expert.focus)}</p><h3>{expert.name}{expert.id === 'hung-jr-shiu' && !isEnglish && <span>許宏誌</span>}</h3><p className="pqc-degree">{t(expert.degree)}</p></div></div><p className="pqc-expertise">{t(expert.expertise)}</p><p className="pqc-muted">{t(expert.detail)}</p><a className="pqc-text-link" href={expert.href} target="_blank" rel="noopener noreferrer">{t(expert.source)}<ArrowUpRight size={16} aria-hidden="true"/></a></article>)}</div><div className="pqc-research" id="pqc-research"><div><p className="pqc-eyebrow">SELECTED RESEARCH / HUNG-JR SHIU</p><h3>{t(['FIPS 204 ML-DSA 後量子數位簽章實作', 'FIPS 204 ML-DSA signature implementation'])}</h3><p>{t(['2026 · 計畫主持人 · HLS 管線化實作', '2026 · Principal investigator · Pipelined HLS implementation'])}</p></div><div><p>{t(['從標準演算法到實作研究，將效能與工程限制納入技術評估。', 'Connect algorithm standards to implementation research, including performance and engineering constraints.'])}</p><a className="pqc-text-link" href="https://scholar.ntpu.edu.tw/en/projects/pipelined-post-quantum-digital-signature-fips-204-ml-dsa-implemen/" target="_blank" rel="noopener noreferrer">{t(['查看大學研究計畫', 'View the university research project'])}<ArrowUpRight size={16} aria-hidden="true"/></a></div></div><p className="pqc-fine">{t(['學術背景與研究可由原始來源核對；大學任職為個人經歷，不表示機構為本服務背書。', 'Academic and research information links to original sources. University affiliations are individual credentials, not institutional endorsement of this service.'])}</p></section>
      <section className="pqc-standards"><div className="pqc-container pqc-standard-grid"><div><ShieldCheck aria-hidden="true"/><h2>{t(['依據 NIST 標準規劃', 'Plan around NIST standards'])}</h2><p>{t(['演算法標準參考，非服務認證', 'Algorithm references, not service certification'])}</p></div>{[['ML-KEM','203','金鑰建立','Key establishment'],['ML-DSA','204','數位簽章','Digital signatures'],['SLH-DSA','205','數位簽章','Digital signatures']].map(([name,num,zh,en])=><a key={num} href={`https://csrc.nist.gov/pubs/fips/${num}/final`} target="_blank" rel="noopener noreferrer"><strong>{name}<ArrowUpRight size={16} aria-hidden="true"/></strong><span>FIPS {num} · {isEnglish?en:zh}</span></a>)}</div></section>
      <section className="pqc-container pqc-section" id="pqc-services"><p className="pqc-eyebrow">02 / SERVICES & DELIVERABLES</p><h2>{t(['每一階段，都有可審查的交付。', 'Reviewable deliverables at every stage.'])}</h2><div className="pqc-phase-tabs" role="group" aria-label={t(['服務階段', 'Service stages'])}>{pqcPhases.map((item,i)=><button key={item.id} data-phase={i} aria-pressed={phase===i} aria-controls="pqc-phase-detail" onClick={()=>setPhase(i)}><span>0{i+1}</span>{t(item.label)}<ArrowRight size={18} aria-hidden="true"/></button>)}</div><div className="pqc-phase-detail" id="pqc-phase-detail" aria-live="polite"><div><h3>{t(activePhase.title)}</h3><p className="pqc-muted">{t(activePhase.description)}</p></div><div className="pqc-card"><p className="pqc-eyebrow">{t(['你的交付物', 'Your deliverables'])}</p><ul>{activePhase.items.map(item=><li key={item[1]}><Check aria-hidden="true" size={18}/>{t(item)}</li>)}</ul><p className="pqc-accept"><strong>{t(['驗收重點', 'Acceptance'])}</strong>{t(activePhase.acceptance)}</p></div></div><div className="mt-8 grid gap-4 lg:grid-cols-3" aria-label={t(['全部服務階段摘要', 'All service-stage summaries'])}>{pqcPhases.map(item=><details key={item.id} className="pqc-card"><summary className="cursor-pointer font-semibold">{t(item.label)} · {t(item.title)}</summary><p className="pqc-muted">{t(item.description)}</p><ul>{item.items.map(output=><li key={output[1]}><Check aria-hidden="true" size={17}/>{t(output)}</li>)}</ul><p className="pqc-accept"><strong>{t(['驗收重點', 'Acceptance'])}</strong>{t(item.acceptance)}</p></details>)}</div><p className="pqc-fine">{t(['顧問提供分析、設計與證據審查；正式變更由客戶及指定供應商依授權執行。實作、授權與維運另定範圍。', 'Advisory covers analysis, design, and evidence review. Authorized customer teams and vendors execute production changes; implementation, licenses, and support require an agreed scope.'])}</p></section>
      <section className="pqc-container pqc-section"><p className="pqc-eyebrow">03 / A FOCUSED PILOT</p><h2>{t(['一個場景，把假設變成證據。', 'One scenario. Testable evidence.'])}</h2><div className="pqc-scenario-grid"><div role="group" aria-label={t(['試點場景', 'Pilot scenarios'])}>{pqcScenarios.map((item,i)=><button key={item.id} data-scenario={item.id} aria-pressed={scenario===i} aria-controls="pqc-scenario-detail" onClick={()=>setScenario(i)}>{t(item.label)}<ArrowRight aria-hidden="true" size={18}/></button>)}</div><div className="pqc-card" id="pqc-scenario-detail" aria-live="polite"><h3>{t(activeScenario.title)}</h3><p className="pqc-muted">{t(activeScenario.description)}</p><dl><dt>{t(['觀察重點', 'What to measure'])}</dt><dd>{t(activeScenario.check)}</dd><dt>{t(['範圍提醒', 'Scope consideration'])}</dt><dd>{t(activeScenario.limit)}</dd></dl></div></div><div className="mt-8 grid gap-4 lg:grid-cols-3" aria-label={t(['全部試點情境摘要', 'All pilot-scenario summaries'])}>{pqcScenarios.map(item=><details key={item.id} className="pqc-card"><summary className="cursor-pointer font-semibold">{t(item.label)} · {t(item.title)}</summary><p className="pqc-muted">{t(item.description)}</p><dl><dt>{t(['觀察重點', 'What to measure'])}</dt><dd>{t(item.check)}</dd><dt>{t(['範圍提醒', 'Scope consideration'])}</dt><dd>{t(item.limit)}</dd></dl></details>)}</div></section>
      <section className="pqc-start" id="pqc-start"><div className="pqc-container pqc-start-grid"><div><p className="pqc-eyebrow">04 / YOUR NEXT MOVE</p><h2>{t(['找到你的導入起點。', 'Find your starting point.'])}</h2><p className="pqc-muted">{t(['三個問題，整理一份初步範圍建議，讓下一場內部討論更具體。', 'Answer three questions to prepare a scope for your next internal discussion.'])}</p><p className="pqc-fine">{t(['不需聯絡資料。答案僅在本頁計算，不會隨問答送出。', 'No contact details required. Answers are processed on this page and are not submitted by this questionnaire.'])}</p><a className="pqc-text-link" href={SITE_BOOKING.href} target="_blank" rel="noopener noreferrer">{t(['預約需求討論', 'Book a discovery meeting'])}<ArrowUpRight aria-hidden="true" size={16}/></a></div><form noValidate onSubmit={submit} id="pqc-start-form">{fields.map((field,i)=><div className="pqc-field" key={field.id}><label htmlFor={`pqc-${field.id}`}><span>0{i+1}</span>{t(field.label)}</label><select id={`pqc-${field.id}`} name={field.id} required value={answers[field.id]} aria-invalid={attempted&&!answers[field.id]||undefined} aria-describedby={attempted&&!answers[field.id]?`pqc-${field.id}-error`:undefined} onChange={e=>{setAnswers({...answers,[field.id]:e.target.value});setShowResult(false);setDownloaded(false);}}><option value="">{t(['請選擇', 'Please select'])}</option>{field.options.map(option=><option key={option[0]} value={option[0]}>{option[isEnglish?2:1]}</option>)}</select>{attempted&&!answers[field.id]&&<p className="pqc-error" id={`pqc-${field.id}-error`}>{t(['請選擇一個選項。', 'Please select an option.'])}</p>}</div>)}<button className="pqc-button" type="submit">{t(['產生起點建議', 'Generate guidance'])}<ArrowRight aria-hidden="true" size={18}/></button><p className="pqc-fine">{t(['5 年為問答分流條件，並非標準或法規門檻。', 'Five years is a questionnaire threshold, not a standard or regulatory deadline.'])}</p>{showResult&&<div className="pqc-result" id="pqc-result" tabIndex={-1} ref={resultRef} aria-labelledby="pqc-result-title"><p className="pqc-eyebrow">{t(['你的初步路徑', 'Your initial path'])}</p><h3 id="pqc-result-title">{t(resultTitle)}</h3><p>{t(resultDescription)}</p><p><strong>{t(selectedScenario.label)}</strong><br/>{t(selectedScenario.check)}</p><p>{t(lifetimeNote)}</p><button type="button" className="pqc-text-link" id="pqc-download" onClick={download}><Download aria-hidden="true" size={18}/>{t(['下載範圍摘要', 'Download the scope'])}</button><p className="pqc-fine">{t(limitation)}</p><p role="status">{downloaded?t(['摘要已產生，下載由瀏覽器處理。', 'Summary created. Your browser handles the download.']):''}</p></div>}</form></div></section>
      <section id="pqc-questions" className="pqc-container pqc-section pqc-faq"><div><p className="pqc-eyebrow">05 / QUESTIONS</p><h2>{t(['先把問題說清楚。', 'Make the questions clear.'])}</h2></div><div><ServiceFaqList serviceId="pqc" isEnglish={isEnglish} /><a className="pqc-text-link" href="https://www.nccoe.nist.gov/applied-cryptography/migration-to-pqc" target="_blank" rel="noopener noreferrer">{t(['NIST PQC 遷移專案', 'NIST PQC migration project'])}<ArrowUpRight size={16} aria-hidden="true"/></a></div></section>
    </div>
  </PageShell>;
};
export default PqcAdvisoryPage;
