import React from 'react';
import { useLanguageContext } from '../../contexts/LanguageContext';
import { ActionLink, CheckList, PageHero, PageShell } from './SitePagePrimitives';

const PrivacyPage: React.FC = () => {
  const { isEnglish } = useLanguageContext();
  return <PageShell title={{ zh: '隱私與資料使用｜EudTech', en: 'Privacy and data use | EudTech' }} description={{ zh: 'EudTech 說明詢價資料、客戶來源追蹤、保存與聯絡方式。', en: 'Learn how EudTech handles quote data, customer-source attribution, retention, and contact.' }} path="/privacy">
    <PageHero eyebrow={{ zh: '隱私與資料使用', en: 'Privacy and data use' }} title={{ zh: '資料使用方式清楚可查', en: 'Clear information about data use' }} lead={{ zh: 'EudTech 只在提供詢價、回覆、來源分析與服務改善所需的範圍內處理資料，並保留必要的安全與稽核控制。', en: 'EudTech processes data only as needed for quotes, replies, source analysis, and service improvement, with security and audit controls.' }} isEnglish={isEnglish} actions={<ActionLink href="mailto:info@eudaemonia.tech">info@eudaemonia.tech</ActionLink>} />
    <main className="mx-auto max-w-5xl space-y-16 px-6 py-20 lg:px-8">
      <section><h2 className="text-2xl font-bold">{isEnglish ? 'What information is processed' : '處理哪些資料'}</h2><p className="mt-4 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'Information submitted through the configurator or contact form is used to understand the request, prepare a reply, and maintain the related business record.' : '透過配置器或聯絡表單提交的資料，用於理解需求、準備回覆及保存相關業務紀錄。'}</p><div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 dark:border-slate-800"><div className="grid bg-slate-100 px-5 py-4 text-sm font-semibold dark:bg-slate-900 sm:grid-cols-[0.8fr_1.2fr_1.2fr]"><span>{isEnglish ? 'Category' : '資料類別'}</span><span className="hidden sm:block">{isEnglish ? 'Examples' : '內容範例'}</span><span className="hidden sm:block">{isEnglish ? 'Purpose' : '使用目的'}</span></div>{[
        { c: { zh: '聯絡與公司資料', en: 'Contact and company data' }, e: { zh: '姓名、公司、工作 Email、電話', en: 'Name, company, work email, phone' }, p: { zh: '確認需求、聯絡及提供服務', en: 'Request review, contact, and service delivery' } },
        { c: { zh: '配置與需求資料', en: 'Configuration and request data' }, e: { zh: '產品、數量、工作負載、配置連結與留言', en: 'Products, quantities, workload, configuration URL, and message' }, p: { zh: '技術審查、報價與驗收規劃', en: 'Technical review, quoting, and acceptance planning' } },
        { c: { zh: '來源與裝置事件', en: 'Attribution and device events' }, e: { zh: 'UTM、referrer、click ID、首次與最後有效來源', en: 'UTM, referrer, click ID, first and last non-direct touch' }, p: { zh: '判斷有效管道、避免重複事件及改善網站', en: 'Channel attribution, event deduplication, and site improvement' } },
      ].map((row) => <div key={row.c.zh} className="grid gap-3 border-t border-slate-200 px-5 py-5 text-sm dark:border-slate-800 sm:grid-cols-[0.8fr_1.2fr_1.2fr]"><p className="font-semibold">{isEnglish ? row.c.en : row.c.zh}</p><p className="text-slate-600 dark:text-slate-300"><span className="font-semibold sm:hidden">{isEnglish ? 'Examples: ' : '內容：'}</span>{isEnglish ? row.e.en : row.e.zh}</p><p className="text-slate-600 dark:text-slate-300"><span className="font-semibold sm:hidden">{isEnglish ? 'Purpose: ' : '目的：'}</span>{isEnglish ? row.p.en : row.p.zh}</p></div>)}</div></section>
      <section><h2 className="text-2xl font-bold">{isEnglish ? 'Customer-source attribution' : '客戶來源追蹤'}</h2><p className="mt-4 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'The site may record first touch, last non-direct touch, campaign parameters, referrer, advertising click identifiers, and a customer-selected source. Anonymous identifiers are used to connect a campaign click to a quote request; raw personal email addresses are not placed in public URLs.' : '網站可能記錄首次來源、最後有效非直接來源、活動參數、來源頁、廣告點擊識別碼及客戶自填來源。網站使用匿名識別碼將活動點擊與詢價連結，不把個人電子郵件放入公開網址。'}</p><p className="mt-4 rounded-xl bg-cyan-50 p-5 text-sm leading-7 text-cyan-950 dark:bg-cyan-950/30 dark:text-cyan-100">{isEnglish ? 'Browser attribution data may remain available for up to 90 days so a later quote request can be connected to the original campaign. A customer-provided answer is kept separately as supporting evidence.' : '瀏覽器來源資料最多可保留 90 天，讓後續詢價可以連結原始活動；客戶自行填寫的來源會分開保存，作為補充證據。'}</p></section>
      <section><h2 className="text-2xl font-bold">{isEnglish ? 'Service providers and disclosure' : '服務提供者與資料提供'}</h2><p className="mt-4 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'EudTech may use hosting, analytics, Microsoft 365, email, and customer-record systems to operate the website and respond to requests. Access is limited to the function required for the service. Information is not sold.' : 'EudTech 可能使用網站託管、分析、Microsoft 365、郵件與客戶紀錄系統處理網站及回覆需求；各服務只取得執行功能所需的資料。EudTech 不出售個人資料。'}</p></section>
      <section><h2 className="text-2xl font-bold">{isEnglish ? 'Retention, security, and requests' : '保存、安全與資料請求'}</h2><CheckList isEnglish={isEnglish} items={[{ zh: '詢價及業務紀錄依服務、契約、稽核與法令遵循需要保存；目的消失後會刪除或去識別化。', en: 'Quote and business records are retained for service, contract, audit, and legal needs, then deleted or de-identified when the purpose ends.' }, { zh: '來源證據與詢價事件分開保存，避免只用姓名、公司或學校身分推測來源。', en: 'Source evidence and quote events are kept separately; source is not inferred from a name, company, or affiliation alone.' }, { zh: '使用存取控制、傳輸保護、事件去重與操作紀錄降低未授權使用風險。', en: 'Access control, transport protection, event deduplication, and operation records reduce unauthorised-use risk.' }, { zh: '如需查詢、更正、停止使用或刪除資料，請寄信至 info@eudaemonia.tech。', en: 'For access, correction, restriction, or deletion requests, email info@eudaemonia.tech.' }]} /><p className="mt-8 text-sm text-slate-500 dark:text-slate-400">{isEnglish ? 'Effective date: 16 August 2026. EudTech may update this notice when processing or service providers change.' : '生效日期：2026 年 8 月 16 日。資料處理方式或服務提供者變更時，EudTech 會更新本說明。'}</p></section>
    </main>
  </PageShell>;
};
export default PrivacyPage;
