import React from 'react';
import { useLanguageContext } from '../../contexts/LanguageContext';
import { ActionLink, CheckList, PageHero, PageShell } from './SitePagePrimitives';

const PrivacyPage: React.FC = () => {
  const { isEnglish } = useLanguageContext();
  return <PageShell title={{ zh: '隱私與資料使用｜EudTech', en: 'Privacy and data use | EudTech' }} description={{ zh: 'EudTech 說明詢價資料、客戶來源追蹤、保存與聯絡方式。', en: 'Learn how EudTech handles quote data, customer-source attribution, retention, and contact.' }} path="/privacy">
    <PageHero eyebrow={{ zh: '隱私與資料使用', en: 'Privacy and data use' }} title={{ zh: '資料使用方式清楚可查', en: 'Clear information about data use' }} lead={{ zh: 'EudTech 只在提供詢價、回覆、來源分析與服務改善所需的範圍內處理資料，並保留必要的安全與稽核控制。', en: 'EudTech processes data only as needed for quotes, replies, source analysis, and service improvement, with security and audit controls.' }} isEnglish={isEnglish} actions={<ActionLink href="mailto:info@eudaemonia.tech">info@eudaemonia.tech</ActionLink>} />
    <main className="mx-auto max-w-4xl space-y-14 px-6 py-20 lg:px-8"><section><h2 className="text-2xl font-bold">{isEnglish ? 'Quote and contact information' : '詢價與聯絡資料'}</h2><p className="mt-4 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'Information submitted through the configurator or contact form is used to understand the request, prepare a reply, and maintain the related business record.' : '透過配置器或聯絡表單提交的資料，用於理解需求、準備回覆及保存相關業務紀錄。'}</p></section><section><h2 className="text-2xl font-bold">{isEnglish ? 'Customer-source attribution' : '客戶來源追蹤'}</h2><p className="mt-4 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'The site may record first touch, last non-direct touch, campaign parameters, referrer, advertising click identifiers, and a customer-selected source. Anonymous identifiers are used to connect a campaign click to a quote request; raw personal email addresses are not placed in public URLs.' : '網站可能記錄首次來源、最後有效非直接來源、活動參數、來源頁、廣告點擊識別碼及客戶自填來源。網站使用匿名識別碼將活動點擊與詢價連結，不把個人電子郵件放入公開網址。'}</p></section><section><h2 className="text-2xl font-bold">{isEnglish ? 'Retention and requests' : '保存與資料請求'}</h2><CheckList isEnglish={isEnglish} items={[{ zh: '只保存提供服務、來源歸因、稽核與法令遵循所需資料。', en: 'Retain only data needed for service, attribution, audit, and legal compliance.' }, { zh: '來源證據與詢價事件分開保存，避免以姓名或學校身分推測來源。', en: 'Keep source evidence and quote events separately; do not infer source from name or affiliation.' }, { zh: '如需查詢、更正或刪除資料，請寄信至 info@eudaemonia.tech。', en: 'For access, correction, or deletion requests, email info@eudaemonia.tech.' }]} /></section></main>
  </PageShell>;
};
export default PrivacyPage;
