import React from 'react';
import { AlertTriangle, BellRing, Fingerprint, Network, Radar, ScanFace, ShieldCheck } from 'lucide-react';
import { useLanguageContext } from '../../contexts/LanguageContext';
import { VENDOR_EVIDENCE } from '../../data/vendorEvidence';
import { ActionLink, CheckList, PageHero, PageShell, SourceLink, tx, VendorMedia } from './SitePagePrimitives';

const SocialIntelligenceSolutionPage: React.FC = () => {
  const { isEnglish } = useLanguageContext();
  const capabilities = [
    { icon: Fingerprint, title: { zh: '帳號真實性與行為', en: 'Profile authenticity and behaviour' }, body: { zh: '依帳號行為與特徵找出可疑或不真實帳號。分析人員可檢視判斷理由與內容活動。', en: 'Flag suspicious or inauthentic profiles from their behaviour and attributes. Analysts can review the reasons and the content activity.' } },
    { icon: Radar, title: { zh: '敘事、情緒與擴散', en: 'Narratives, sentiment, and spread' }, body: { zh: '持續追蹤重要議題、品牌敘事與情緒變化。掌握討論量與內容擴散狀況。', en: 'Track key topics, brand narratives, and sentiment shifts over time. See conversation volume and how far content spreads.' } },
    { icon: Network, title: { zh: '協調式活動分析', en: 'Coordinated activity analysis' }, body: { zh: '找出在時間、內容與帳號關係上協同行動的群組。作為傳播路徑調查的起點。', en: 'Identify groups that act in concert across timing, content, and profile relationships. Use them as the starting point for propagation analysis.' } },
    { icon: BellRing, title: { zh: '即時敘事警示', en: 'Real-time narrative alerts' }, body: { zh: '先設定重要敘事與風險條件。內容量、情緒或異常活動達到條件時，通知負責人。', en: 'Define the narratives and risk conditions that matter. When volume, sentiment, or anomalous activity crosses the threshold, the owner is notified.' } },
    { icon: ScanFace, title: { zh: '冒名與 AI 內容風險', en: 'Impersonation and AI-content risk' }, body: { zh: '協助辨識品牌冒名與假帳號。深偽與 AI 生成內容風險以原廠公開能力為範圍。', en: 'Help detect brand impersonation and fake profiles. Deepfake and AI-generated content risk is covered within the vendor’s published capabilities.' } },
    { icon: ShieldCheck, title: { zh: '決策用情報交付', en: 'Decision-ready intelligence' }, body: { zh: '把帳號、內容、敘事與協調證據整理成摘要。公關、資安、政策與管理團隊可直接據以行動。', en: 'Turn profile, content, narrative, and coordination evidence into a brief. Communications, security, policy, and leadership teams can act on it directly.' } }
  ];
  const accessModels = [
    { title: { zh: 'SaaS 平台', en: 'SaaS platform' }, body: { zh: '授權使用者自行設定議題、執行分析與檢視報表。', en: 'Authorised users set up topics, run analysis, and review reports themselves.' } },
    { title: { zh: 'Managed Services', en: 'Managed Services' }, body: { zh: '原廠或服務團隊協助監測、分析與產出情報。適合需要分析人力支援的組織。', en: 'The vendor or a service team supports monitoring, analysis, and intelligence production. For organisations that need analyst support.' } },
    { title: { zh: '即時警示', en: 'Real-time alerts' }, body: { zh: '依設定的敘事與風險條件發出事件通知。負責人可快速檢視並回應。', en: 'Event notifications follow the defined narrative and risk conditions. Owners can review and respond quickly.' } },
    { title: { zh: 'On-Prem 與 API', en: 'On-prem and API' }, body: { zh: '原廠公開提供地端與 API 存取方向。實際範圍依需求、授權與整合條件確認。', en: 'The vendor publicly lists on-prem and API access directions. Actual scope depends on requirements, licensing, and integration conditions.' } }
  ];
  const cases = [
    { name: 'U.S. State Department', body: { zh: 'Cyabra 原廠案例頁公開列示的公部門案例。可作為政府資訊環境與假資訊分析需求的參考。', en: 'A public-sector case listed on Cyabra’s official case-study page. A reference for government information-environment and disinformation analysis.' } },
    { name: 'WarnerMedia', body: { zh: 'Cyabra 原廠案例頁公開列示的企業案例。可作為品牌、內容與受眾真實性分析需求的參考。', en: 'An enterprise case listed on Cyabra’s official case-study page. A reference for brand, content, and audience-authenticity analysis.' } }
  ];

  return <PageShell title={{ zh: '社群情報與品牌保護｜EudTech', en: 'Social intelligence and brand protection | EudTech' }} description={{ zh: 'EudTech 以 Cyabra 協助企業與公部門分析假資訊、假帳號、敘事、協調式社群行為與品牌風險。', en: 'EudTech uses Cyabra to help enterprises and public institutions analyse disinformation, fake profiles, narratives, coordinated social behaviour, and brand risk.' }} path="/solutions/social-intelligence">
    <PageHero eyebrow={{ zh: '社群情報', en: 'Social intelligence' }} title={{ zh: '看見敘事背後的帳號與協調行為', en: 'See the profiles and coordination behind the narrative' }} lead={{ zh: '社群內容變動快，品牌、公關、資安與公部門需要快速判斷風險。EudTech 以 Cyabra 平台把內容整理成情報。來源可檢視、風險可判斷、回應可安排。', en: 'Social content moves fast, and brand, communications, security, and public-sector teams must judge risk quickly. EudTech uses the Cyabra platform to turn that content into intelligence with reviewable sources, assessable risk, and response options.' }} isEnglish={isEnglish} image="/brand-provenance/eudtech-brand-social.webp" imageAlt={{ zh: '社群訊息、帳號關係與風險決策的品牌情境圖', en: 'Brand scene of social signals, profile relationships, and risk decisions' }} imagePosition="center" actions={<ActionLink href="/contact">{isEnglish ? 'Request an intelligence consultation' : '預約情報諮詢'}</ActionLink>} />

    <section className="py-20"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">Cyabra</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">{isEnglish ? 'Start with authenticity, then trace the narrative' : '先判斷真實性，再追查敘事與擴散'}</h2><p className="mt-5 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'Cyabra combines profile authenticity, content analysis, narrative monitoring, coordination detection, and alerts. Analysts still review the evidence and decide the response.' : 'Cyabra 整合帳號真實性、內容分析、敘事監測、協調行為偵測與警示。分析人員仍需檢視證據並決定回應方式。'}</p><div className="mt-7"><SourceLink href={VENDOR_EVIDENCE.cyabra.sources.authenticity.href} label={VENDOR_EVIDENCE.cyabra.sources.authenticity.label} isEnglish={isEnglish} /></div></div><VendorMedia src={VENDOR_EVIDENCE.cyabra.images.profiles} alt={{ zh: 'Cyabra 原廠帳號真實性與行為分析介面', en: 'Official Cyabra profile authenticity and behaviour analysis interface' }} caption={{ zh: '原廠公開介面：帳號真實性、行為與判斷理由。', en: 'Official interface: profile authenticity, behaviour, and analysis reasons.' }} sourceHref={VENDOR_EVIDENCE.cyabra.sources.authenticity.href} sourceLabel={VENDOR_EVIDENCE.cyabra.sources.authenticity.label} isEnglish={isEnglish} contain /></div></div></section>

    <section className="border-y border-slate-200 bg-slate-50 py-20 dark:border-slate-800 dark:bg-slate-900/60"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">{isEnglish ? 'Platform capabilities' : '平台能力'}</p><h2 className="mt-4 text-3xl font-bold tracking-tight">{isEnglish ? 'Answer six operational questions' : '回答六個實際工作問題'}</h2></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{capabilities.map(({ icon: Icon, title, body }) => <article key={tx(title, isEnglish)} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm dark:border-slate-800 dark:bg-slate-950"><Icon className="h-7 w-7 text-cyan-600 dark:text-cyan-300" /><h3 className="mt-5 text-xl font-semibold">{tx(title, isEnglish)}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{tx(body, isEnglish)}</p></article>)}</div></div></section>

    <section className="py-20"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-2"><VendorMedia src={VENDOR_EVIDENCE.cyabra.images.volume} alt={{ zh: 'Cyabra 原廠內容真實性與數量分析畫面', en: 'Official Cyabra content authenticity and volume analysis screen' }} caption={{ zh: '內容量依真實、可疑與不真實分類檢視。', en: 'Content volume reviewed by authentic, suspicious, and inauthentic categories.' }} sourceHref={VENDOR_EVIDENCE.cyabra.sources.authenticity.href} sourceLabel={VENDOR_EVIDENCE.cyabra.sources.authenticity.label} isEnglish={isEnglish} contain /><VendorMedia src={VENDOR_EVIDENCE.cyabra.images.topics} alt={{ zh: 'Cyabra 原廠議題擴散分析畫面', en: 'Official Cyabra topic-proliferation analysis screen' }} caption={{ zh: '議題與內容擴散關係的原廠公開介面。', en: 'Official interface for topic and content proliferation relationships.' }} sourceHref={VENDOR_EVIDENCE.cyabra.sources.coordination.href} sourceLabel={VENDOR_EVIDENCE.cyabra.sources.coordination.label} isEnglish={isEnglish} contain /></div><p className="mt-6 text-center text-xs leading-6 text-slate-500 dark:text-slate-400">{isEnglish ? 'Screens are official vendor visuals for capability illustration. Actual fields and access depend on the contracted Cyabra edition and data scope.' : '畫面為原廠公開能力示意；實際欄位與存取範圍依採購的 Cyabra 版本及資料範圍確認。'}</p></div></section>

    <section className="border-y border-slate-200 bg-slate-50 py-20 dark:border-slate-800 dark:bg-slate-900/60"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-3xl"><h2 className="text-3xl font-bold tracking-tight">{isEnglish ? 'Select the access model that matches the team' : '依團隊能力選擇使用方式'}</h2><p className="mt-5 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'Cyabra publicly offers managed service, real-time alerts, SaaS, on-premises, and API access directions. EudTech confirms the suitable licensing and delivery model during discovery.' : 'Cyabra 原廠公開提供 Managed Services、即時警示、SaaS、On-Prem 與 API 等使用方向。EudTech 會在需求訪談時確認適合的授權與交付模式。'}</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{accessModels.map((item) => <article key={tx(item.title, isEnglish)} className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-950"><h3 className="font-semibold">{tx(item.title, isEnglish)}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{tx(item.body, isEnglish)}</p></article>)}</div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-3"><SourceLink href={VENDOR_EVIDENCE.cyabra.sources.corporateComms.href} label={VENDOR_EVIDENCE.cyabra.sources.corporateComms.label} isEnglish={isEnglish} /><SourceLink href={VENDOR_EVIDENCE.cyabra.sources.alerts.href} label={VENDOR_EVIDENCE.cyabra.sources.alerts.label} isEnglish={isEnglish} /><SourceLink href={VENDOR_EVIDENCE.cyabra.sources.publicSector.href} label={VENDOR_EVIDENCE.cyabra.sources.publicSector.label} isEnglish={isEnglish} /></div></div></section>

    <section className="py-20"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2 lg:px-8"><div><AlertTriangle className="h-8 w-8 text-cyan-600 dark:text-cyan-300" /><h2 className="mt-5 text-3xl font-bold">{isEnglish ? 'Define the decision before the deliverable' : '先定義決策，再定義交付'}</h2><p className="mt-5 leading-8 text-slate-600 dark:text-slate-300">{isEnglish ? 'EudTech first aligns the monitoring question, audience, evidence standard, escalation path, and response owner. Only then is the intelligence output defined.' : 'EudTech 先對齊監測問題、目標對象、證據標準、升級路徑與回應負責人。之後才定義情報交付格式。'}</p></div><CheckList isEnglish={isEnglish} items={[{ zh: '釐清品牌、事件、人物、政策或市場議題', en: 'Define the brand, event, person, policy, or market question' }, { zh: '設定關鍵字、語言、平台、期間與風險條件', en: 'Set keywords, languages, platforms, time range, and risk conditions' }, { zh: '分析帳號真實性、敘事、情緒與擴散關係', en: 'Analyse profile authenticity, narratives, sentiment, and spread relationships' }, { zh: '由人員檢視證據並決定是否升級或回應', en: 'Have analysts review evidence and decide whether to escalate or respond' }, { zh: '交付摘要、來源、事件時間線與後續追蹤項目', en: 'Deliver a brief, sources, event timeline, and follow-up items' }]} /></div></section>

    <section className="border-y border-slate-200 bg-slate-50 py-20 dark:border-slate-800 dark:bg-slate-900/60"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">{isEnglish ? 'Vendor-published cases' : '原廠公開案例'}</p><h2 className="mt-4 text-3xl font-bold tracking-tight">{isEnglish ? 'Examples published by Cyabra' : 'Cyabra 公開的應用參考'}</h2></div><SourceLink href={VENDOR_EVIDENCE.cyabra.sources.cases.href} label={VENDOR_EVIDENCE.cyabra.sources.cases.label} isEnglish={isEnglish} /></div><div className="mt-10 grid gap-5 md:grid-cols-2">{cases.map((item) => <article key={item.name} className="rounded-2xl border border-slate-200 bg-white p-7 dark:border-slate-800 dark:bg-slate-950"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-700 dark:text-cyan-300">{isEnglish ? 'Cyabra case study' : 'Cyabra 原廠案例'}</p><h3 className="mt-4 text-2xl font-semibold">{item.name}</h3><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">{tx(item.body, isEnglish)}</p></article>)}</div></div></section>

    <section className="bg-slate-950 py-16 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-7 px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><h2 className="text-3xl font-bold">{isEnglish ? 'Start with one issue and one decision owner' : '從一個議題與一位決策負責人開始'}</h2><p className="mt-3 max-w-2xl leading-7 text-slate-300">{isEnglish ? 'EudTech will define the monitoring question, evidence, output, licensing direction, and pilot scope.' : 'EudTech 會確認監測問題、證據、交付格式、授權方向與試點範圍。'}</p></div><ActionLink href="/contact">{isEnglish ? 'Request a consultation' : '預約情報諮詢'}</ActionLink></div></section>
  </PageShell>;
};
export default SocialIntelligenceSolutionPage;
