// 技術規格翻譯表
export const technicalSpecsTranslations: Record<string, string> = {
  'Motherboards': '主機板',
  'Motherboard': '主機板',
  'RAM': '記憶體',
  'Memory': '記憶體',
  'M2 drives': 'M.2硬碟',
  'Drives': '硬碟',
  'Storage': '儲存設備',
  'PSU and Operating voltage': '電源供應與操作電壓',
  'Power Supply System': '電源供應系統',
  'Power': '電源',
  'Cooling Capacity': '散熱能力',
  'Cooling': '散熱',
  'Noise level': '噪音等級',
  'LAN': '網路介面',
  'Network': '網路',
  'OS': '作業系統',
  'Liquid cooling': '液冷系統',
  'Reservoir': '水箱',
  'Pumps': '水泵',
  'Radiators': '散熱器',
  'Fans': '風扇',
  'Installation': '安裝方式',
  'Required rack space': '機架空間需求',
  'Size': '尺寸',
  'Weight': '重量',
  'Operating & storage temperature range': '操作與存儲溫度範圍',
  'Form Factor': '機箱規格',
  'GPUs': 'GPU',
  'GPU': 'GPU',
  'Product Series': '產品系列',
  'Processor': '處理器',
  'CPU': '處理器',
  'Maximum Cooling Capacity': '最大散熱能力',
  'Liquid Cooling': '液冷系統',
  'Internal Storage Interface': '內部儲存介面',
  'Expansion Slots': '擴充插槽',
  'Connectivity': '連接選項',
  'Management': '管理功能',
  'Security': '安全功能',
  'Dimensions': '尺寸',
  'Warranty': '保固'
};

export const orderInfoTypeTranslations: Record<string, string> = {
  'LIQUID COOLED': '液冷系統',
  'QUICK-DISCONNECT COUPLINGS': '快速接頭設計',
  'REMOTE MANAGEMENT': '遠端管理',
  "COMINO'S MONITORING SYSTEM": 'Comino監控系統',
  'BASE SYSTEM': '基本系統',
  'EXPANSION KIT': '擴充套件',
  'RACK ASSEMBLY': '機架安裝',
  'SUPPORT PACKAGE': '技術支援套件',
  'NETWORKING': '網路配置',
  'CUSTOM CONFIGURATION': '客製化配置'
};

export const formatConfigType: Record<string, string> = {
  'LIQUID COOLED': 'Liquid Cooling System',
  'QUICK-DISCONNECT COUPLINGS': 'Quick-Disconnect Couplings',
  'REMOTE MANAGEMENT': 'Remote Management',
  "COMINO'S MONITORING SYSTEM": 'Comino Monitoring System',
  'BASE SYSTEM': 'Base System',
  'EXPANSION KIT': 'Expansion Kit',
  'RACK ASSEMBLY': 'Rack Assembly',
  'SUPPORT PACKAGE': 'Support Package',
  'NETWORKING': 'Networking',
  'CUSTOM CONFIGURATION': 'Custom Configuration'
};
